### ISSUE TITLE
[Feature] 🚀 Support all YARRRML keys

### ISSUE THREAD

**Issue by benj-moreau** [ftourer/MappingQueryFinder#1]
For the moment, this code supports only 1 version of yarrml keys (`mappings`, `predicateobjects`, etc.)

To support all YARRRML keys, you can use the YARRRML_KEYS dict:

```python
YARRRML_KEYS = {
    'mappings': ['mappings', 'mapping'],
    'predicateobjects': ['predicateobjects', 'predicateobject', 'po'],
    'predicates': ['predicates', 'predicate', 'p'],
    'objects': ['objects', 'object', 'o'],
    'value': ['value', 'v']
}
```
along with the following function:

```python
def get_keys(d, key):
    # Get the value of the first key in corresponding YARRRML_KEYS that match a key in d
    if key in YARRRML_KEYS:
        for yarrrml_key in YARRRML_KEYS[key]:
            if yarrrml_key in d:
                return d[key]
    return {}
```

then, it should support mappings like:

```yaml
mapping:
  engine:
    po:
      - [a, 'https://schema.org/EngineSpecification']
      - [a, 'http://dbpedia.org/ontology/Engine']
      - [a, 'http://dbpedia.org/ontology/Device']
      - ['http://www.w3.org/2000/01/rdf-schema#label', $(engid) $(fueltype) $(trany) $(cylinders)cyl $(displ)]
      - ['https://auto.schema.org/engineType', $(eng_dscr)]
      - ['http://dbpedia.org/ontology/cylinderCount', $(cylinders)]
      - ['https://auto.schema.org/engineDisplacement', $(displ)]
    source: dataset-source
    subject: https://data.opendatasoft.com/ld/resources/all-vehicles-model@public/Engine/$(engid)/
...
```
